#pragma once

enum KeStatus
{
	STATUS_FAILURE,
	STATUS_SUCCESS,
	STATUS_UNEXPECTED,

	STATUS_INVALID_PARAMETER,
	STATUS_NULL_PARAMETER,

	STATUS_ALLOC_FAILED,

	STATUS_PROCESS_NOT_FOUND,
} typedef KeStatus;

#define FAILED(status) (status != STATUS_SUCCESS)